const elements = [
    // 第一周期
    {
        number: 1,
        symbol: "H",
        name: "氢",
        chineseName: "氢",
        weight: "1.008",
        category: "nonmetal",
        group: 1, 
        period: 1,
        discoverer: "亨利·卡文迪许",
        year: "1766",
        story: "卡文迪许在实验中发现当金属与酸反应时会产生一种轻质可燃气体，他称之为'可燃气'。后来拉瓦锡将其命名为'氢'(Hydrogen)，意为'产生水的元素'。氢是宇宙中最丰富、最简单的元素。",
        imageUrl: "https://images.unsplash.com/photo-1601964164741-bacb755e0270?w=600&auto=format&fit=crop",
        videoUrl: "https://www.youtube.com/embed/qNFUzgDxCeM"
    },
    {
        number: 2,
        symbol: "He",
        name: "Helium",
        chineseName: "氦",
        weight: "4.0026",
        category: "noble-gas",
        group: 18, 
        period: 1,
        discoverer: "皮埃尔·詹森",
        year: "1868",
        story: "1868年，法国天文学家詹森在观测太阳日食时，在太阳光谱中发现了一条从未在地球元素中观察到的黄线。这种元素被命名为'氦'(Helium)，来源于希腊语中'太阳'的意思。直到1895年，氦才在地球上的矿物中被发现。",
        imageUrl: "https://images.unsplash.com/photo-1527409024723-033dddf9f9d4?w=600&auto=format&fit=crop"
    },
    
    // 第二周期
    {
        number: 3,
        symbol: "Li",
        name: "Lithium",
        chineseName: "锂",
        weight: "6.94",
        category: "alkali-metal",
        group: 1, 
        period: 2,
        discoverer: "约翰·奥古斯特·阿尔弗德松",
        year: "1817",
        story: "锂元素于1817年由瑞典化学家阿尔弗德松在矿石中发现。他注意到这种新元素的化合物在火焰中呈现美丽的红色。'锂'(Lithium)这个名字来源于希腊语'lithos'，意为'石头'，因为它是在岩石中发现的。",
        imageUrl: "https://images.unsplash.com/photo-1563905457637-f76e198b8107?w=600&auto=format&fit=crop"
    },
    {
        number: 4,
        symbol: "Be",
        name: "Beryllium",
        chineseName: "铍",
        weight: "9.0122",
        category: "alkaline-earth",
        group: 2, 
        period: 2,
        discoverer: "路易·尼古拉·沃克兰",
        year: "1798",
        story: "1798年，法国化学家沃克兰从绿柱石和祖母绿中分离出了一种新的氧化物，他将其命名为'甜土'，因为它的盐有甜味。后来这种元素被命名为'铍'(Beryllium)，来源于绿柱石的希腊名称'beryllos'。",
        imageUrl: "https://images.pexels.com/photos/163016/emerald-green-gem-jewel-163016.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        number: 5,
        symbol: "B",
        name: "Boron",
        chineseName: "硼",
        weight: "10.81",
        category: "metalloid",
        group: 13, 
        period: 2,
        discoverer: "约瑟夫·路易·盖-吕萨克和路易·雅克·泰纳德",
        year: "1808",
        story: "硼元素在1808年由法国科学家盖-吕萨克和泰纳德共同发现。他们通过用钾还原硼酸，获得了不纯的硼。'硼'(Boron)这个名字来源于阿拉伯语'buraq'，指的是硼砂。硼在很多日常用品中都有应用，如玻璃、洗涤剂等。",
        imageUrl: "https://images.pexels.com/photos/4347867/pexels-photo-4347867.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        number: 6,
        symbol: "C",
        name: "Carbon",
        chineseName: "碳",
        weight: "12.011",
        category: "nonmetal",
        group: 14, 
        period: 2,
        discoverer: "古代已知",
        year: "古代",
        story: "碳元素自古以来就以木炭、煤和钻石等形式被人类所熟知。古埃及人早在公元前3750年就已经用木炭冶炼铜。'碳'(Carbon)这个名字来源于拉丁语'carbo'，意为'木炭'。碳是生命的基础元素，也是有机化学的核心。",
        imageUrl: "https://images.unsplash.com/photo-1565807159948-4276f785d567?w=600&auto=format&fit=crop",
        videoUrl: "https://www.youtube.com/embed/YQJ0x_jlBfE"
    },
    {
        number: 7,
        symbol: "N",
        name: "Nitrogen",
        chineseName: "氮",
        weight: "14.007",
        category: "nonmetal",
        group: 15, 
        period: 2,
        discoverer: "丹尼尔·卢瑟福",
        year: "1772",
        story: "1772年，苏格兰医生卢瑟福发现空气中存在一种气体，不支持燃烧也不支持呼吸。他将这种气体称为'有害空气'。后来拉瓦锡将其命名为'氮'(Nitrogen)，意为'无生命的'。氮气占地球大气的78%。",
        imageUrl: "https://images.unsplash.com/photo-1628863353691-0829ae9e6400?w=600&auto=format&fit=crop"
    },
    {
        number: 8,
        symbol: "O",
        name: "Oxygen",
        chineseName: "氧",
        weight: "15.999",
        category: "nonmetal",
        group: 16, 
        period: 2,
        discoverer: "卡尔·威廉·舍勒",
        year: "1771",
        story: "氧气最早于1771年由瑞典药剂师舍勒发现，但他的发现直到1777年才发表。同时，英国科学家普利斯特利于1774年独立发现了氧气，并将其结果先于舍勒发表。拉瓦锡后来将这种气体命名为'氧'(Oxygen)，意为'酸的生成者'。",
        imageUrl: "https://images.unsplash.com/photo-1607619020098-278a114438e9?w=600&auto=format&fit=crop"
    },
    {
        number: 9,
        symbol: "F",
        name: "Fluorine",
        chineseName: "氟",
        weight: "18.998",
        category: "nonmetal",
        group: 17, 
        period: 2,
        discoverer: "亨利·莫瓦桑",
        year: "1886",
        story: "氟是最活泼的元素之一，这使得它难以被分离出来。许多科学家在尝试分离氟的过程中遭受了严重伤害。最终，法国化学家莫瓦桑在1886年成功地通过电解氟化氢得到了纯氟。'氟'(Fluorine)这个名字来源于拉丁语'fluere'，意为'流动'。",
        imageUrl: "https://images.pexels.com/photos/3014893/pexels-photo-3014893.jpeg?auto=compress&cs=tinysrgb&w=600"
    },
    {
        number: 10,
        symbol: "Ne",
        name: "Neon",
        chineseName: "氖",
        weight: "20.180",
        category: "noble-gas",
        group: 18, 
        period: 2,
        discoverer: "威廉·拉姆齐和莫里斯·特拉沃斯",
        year: "1898",
        story: "氖元素于1898年由英国科学家拉姆齐和特拉沃斯在研究液态空气时发现。'氖'(Neon)这个名字来源于希腊语'neos'，意为'新的'。氖是第一个被发现会发光的气体，现在广泛用于霓虹灯中，给城市带来了五彩缤纷的夜景。",
        imageUrl: "https://images.unsplash.com/photo-1621155346337-1d19476ba7d6?w=600&auto=format&fit=crop"
    },

    // 这里只包含前20个元素作为示例，实际应用中可以添加全部118个元素
    // 第三周期
    {
        number: 11,
        symbol: "Na",
        name: "Sodium",
        chineseName: "钠",
        weight: "22.990",
        category: "alkali-metal",
        group: 1, 
        period: 3,
        discoverer: "汉弗莱·戴维",
        year: "1807",
        story: "1807年，英国化学家戴维通过电解熔融的氢氧化钠成功分离出了钠金属。他观察到这种新金属非常活泼，会在空气中迅速氧化。'钠'(Sodium)这个名字来源于阿拉伯语'suda'，意为'头痛的治疗'，因为钠的碳酸盐被用作治疗头痛的药物。",
        imageUrl: "https://images.unsplash.com/photo-1623640094594-572cb802c0bd?w=600&auto=format&fit=crop",
        videoUrl: "https://www.youtube.com/embed/oqMN3y8k9So"
    },
    {
        number: 12,
        symbol: "Mg",
        name: "Magnesium",
        chineseName: "镁",
        weight: "24.305",
        category: "alkaline-earth",
        group: 2, 
        period: 3,
        discoverer: "约瑟夫·布莱克",
        year: "1755",
        story: "1755年，苏格兰化学家布莱克首次认识到氧化镁与石灰是不同的物质。1808年，戴维通过电解氧化镁首次制备出不纯的镁。'镁'(Magnesium)这个名字来源于希腊语'magnesia'，这是一个古代城市名，那里出产含镁的矿物。",
        imageUrl: "https://images.unsplash.com/photo-1556227834-09f1de5c1cea?w=600&auto=format&fit=crop"
    },
    {
        number: 13,
        symbol: "Al",
        name: "Aluminum",
        chineseName: "铝",
        weight: "26.982",
        category: "post-transition-metal",
        group: 13, 
        period: 3,
        discoverer: "汉斯·克里斯蒂安·厄斯特德",
        year: "1825",
        story: "虽然铝化合物自古以来就被用于染料和药物，但纯铝直到1825年才被丹麦科学家厄斯特德首次分离出来。由于制备纯铝的困难，铝曾一度比黄金还贵重。1886年，霍尔和埃鲁发明了电解法生产铝，使铝成为常见金属。'铝'(Aluminum)这个名字来源于拉丁语'alumen'，指的是明矾。",
        imageUrl: "https://images.unsplash.com/photo-1602383247837-51c566bf2e49?w=600&auto=format&fit=crop"
    },
    {
        number: 14,
        symbol: "Si",
        name: "Silicon",
        chineseName: "硅",
        weight: "28.085",
        category: "metalloid",
        group: 14, 
        period: 3,
        discoverer: "约恩斯·雅各布·贝采利乌斯",
        year: "1824",
        story: "1824年，瑞典化学家贝采利乌斯通过加热氟硅酸钾与钾得到了非晶态硅。'硅'(Silicon)这个名字来源于拉丁语'silex'或'silicis'，意为'燧石'。硅是地球地壳中第二丰富的元素，现代电子工业的基础。",
        imageUrl: "https://images.unsplash.com/photo-1573663520878-8a98bb0f8cb5?w=600&auto=format&fit=crop"
    },
    {
        number: 15,
        symbol: "P",
        name: "Phosphorus",
        chineseName: "磷",
        weight: "30.974",
        category: "nonmetal",
        group: 15, 
        period: 3,
        discoverer: "亨宁·布兰德",
        year: "1669",
        story: "磷是第一个被发现的不是自古就知道的元素。1669年，德国炼金术士布兰德在尝试从人尿中提取'点石成金'的物质时，意外发现了一种在黑暗中发光的物质，他将其命名为'磷'(Phosphorus)，源自希腊语'带来光明的'。白磷在空气中会自燃，这使得它成为火柴的重要成分。",
        imageUrl: "https://images.unsplash.com/photo-1515444347446-4347d4c95fd1?w=600&auto=format&fit=crop"
    },
    {
        number: 16,
        symbol: "S",
        name: "Sulfur",
        chineseName: "硫",
        weight: "32.06",
        category: "nonmetal",
        group: 16, 
        period: 3,
        discoverer: "古代已知",
        year: "古代",
        story: "硫元素自古以来就以单质形式为人所知，古埃及人早在公元前2000年就使用硫磺进行熏蒸和漂白。'硫'(Sulfur)这个名字可能来源于梵语'sulvere'，或拉丁语'sulphurium'。古代人认为硫磺的气味与地狱有关，因此它也被称为'地狱之火'。"
    },
    {
        number: 17,
        symbol: "Cl",
        name: "Chlorine",
        chineseName: "氯",
        weight: "35.45",
        category: "nonmetal",
        group: 17, 
        period: 3,
        discoverer: "卡尔·威廉·舍勒",
        year: "1774",
        story: "1774年，瑞典化学家舍勒在实验中加热二氧化锰与盐酸，产生了一种黄绿色的气体。他将这种气体称为'脱色酸气'，因为它有漂白的能力。戴维于1810年确认它是一种元素，并将其命名为'氯'(Chlorine)，来源于希腊语'chloros'，意为'黄绿色'。"
    },
    {
        number: 18,
        symbol: "Ar",
        name: "Argon",
        chineseName: "氩",
        weight: "39.948",
        category: "noble-gas",
        group: 18, 
        period: 3,
        discoverer: "约翰·威廉·斯特拉特和威廉·拉姆齐",
        year: "1894",
        story: "1894年，英国物理学家斯特拉特和化学家拉姆齐发现空气中含有一种之前未知的惰性气体。他们将这种气体命名为'氩'(Argon)，来源于希腊语'argos'，意为'懒惰的'，因为这种气体几乎不与其他物质发生化学反应。氩约占地球大气的0.93%。"
    },
    
    // 第四周期的开始
    {
        number: 19,
        symbol: "K",
        name: "Potassium",
        chineseName: "钾",
        weight: "39.098",
        category: "alkali-metal",
        group: 1, 
        period: 4,
        discoverer: "汉弗莱·戴维",
        year: "1807",
        story: "1807年，英国化学家戴维使用刚发明不久的电池，通过电解熔融的氢氧化钾分离出了钾金属。这种新金属非常活泼，甚至能与水剧烈反应并释放足够的热量点燃产生的氢气。'钾'(Potassium)这个名字来源于'pot ash'(锅灰)，因为钾化合物可以从木灰中提取。"
    },
    {
        number: 20,
        symbol: "Ca",
        name: "Calcium",
        chineseName: "钙",
        weight: "40.078",
        category: "alkaline-earth",
        group: 2, 
        period: 4,
        discoverer: "汉弗莱·戴维",
        year: "1808",
        story: "钙化合物如石灰(氧化钙)自古以来就被人类所使用，但钙元素直到1808年才被戴维通过电解石灰分离出来。'钙'(Calcium)这个名字来源于拉丁语'calx'，意为'石灰'。钙是人体中含量最多的金属元素，主要存在于骨骼和牙齿中。"
    },
    
    // 从这里开始添加新元素
    {
        number: 21,
        symbol: "Sc",
        name: "Scandium",
        chineseName: "钪",
        weight: "44.956",
        category: "transition-metal",
        group: 3, 
        period: 4,
        discoverer: "拉尔斯·尼尔松",
        year: "1879",
        story: "1879年，瑞典化学家尼尔松在检查铒的杂质时发现了这种新元素。他将其命名为'钪'(Scandium)，以斯堪的纳维亚半岛(Scandinavia)命名。有趣的是，钪元素的存在和性质在1869年就被门捷列夫所预言，当时他称之为'埃卡硼'。"
    },
    {
        number: 22,
        symbol: "Ti",
        name: "Titanium",
        chineseName: "钛",
        weight: "47.867",
        category: "transition-metal",
        group: 4, 
        period: 4,
        discoverer: "威廉·格雷戈尔",
        year: "1791",
        story: "1791年，英国业余地质学家和牧师格雷戈尔在康沃尔郡的沙滩上发现了一种黑色矿砂，后来从中分离出了一种新的氧化物。但直到1910年，美国冶金学家亨特才制备出纯钛。'钛'(Titanium)这个名字来源于希腊神话中的泰坦巨神族，象征其强度和耐用性。"
    },
    {
        number: 23,
        symbol: "V",
        name: "Vanadium",
        chineseName: "钒",
        weight: "50.942",
        category: "transition-metal",
        group: 5, 
        period: 4,
        discoverer: "尼尔斯·塞夫斯特罗姆",
        year: "1830",
        story: "1830年，瑞典化学家塞夫斯特罗姆在炼铁厂的铁样品中发现了一种新元素，他将其命名为'钒'(Vanadium)，来源于北欧神话中的美丽女神瓦纳迪斯(Vanadis)，因为这种元素形成了美丽的彩色化合物。有趣的是，钒在1801年就被墨西哥矿物学家德尔里奥发现，但他错误地认为它是铬。"
    },
    {
        number: 24,
        symbol: "Cr",
        name: "Chromium",
        chineseName: "铬",
        weight: "51.996",
        category: "transition-metal",
        group: 6, 
        period: 4,
        discoverer: "路易·尼古拉·沃克兰",
        year: "1797",
        story: "1797年，法国化学家沃克兰在西伯利亚铅铬矿中发现了一种新元素。他将其命名为'铬'(Chromium)，来源于希腊语'chroma'，意为'颜色'，因为铬的化合物呈现各种鲜艳的颜色。铬现在广泛用于制造不锈钢和电镀工艺。"
    },
    {
        number: 25,
        symbol: "Mn",
        name: "Manganese",
        chineseName: "锰",
        weight: "54.938",
        category: "transition-metal",
        group: 7, 
        period: 4,
        discoverer: "约翰·戈特利布·甘",
        year: "1774",
        story: "虽然锰矿物自古以来就被用于玻璃制造，但锰元素直到1774年才被瑞典化学家甘分离出来。通过加热二氧化锰和木炭，他获得了一种脆性金属。'锰'(Manganese)这个名字可能来源于意大利语'manganese'或拉丁语'magnes'，意为'磁石'。锰是人体必需的微量元素，对骨骼发育和新陈代谢至关重要。"
    },
    {
        number: 26,
        symbol: "Fe",
        name: "Iron",
        chineseName: "铁",
        weight: "55.845",
        category: "transition-metal",
        group: 8, 
        period: 4,
        discoverer: "古代已知",
        year: "古代",
        story: "铁是最早被人类使用的金属之一，早在公元前4000年就有了铁器。然而，大规模冶炼和使用铁器始于公元前1200年左右的赫梯人。'铁'(Iron)这个词来源于盎格鲁-撒克逊语'iren'。铁是地球核心的主要成分，也是人体中必不可少的元素。",
        imageUrl: "https://images.unsplash.com/photo-1536566482680-fca31930a0bd?w=600&auto=format&fit=crop"
    },
    {
        number: 27,
        symbol: "Co",
        name: "Cobalt",
        chineseName: "钴",
        weight: "58.933",
        category: "transition-metal",
        group: 9, 
        period: 4,
        discoverer: "格奥尔格·布兰特",
        year: "1735",
        story: "1735年，瑞典化学家布兰特在分析含砷的铜矿时发现了钴。'钴'(Cobalt)这个名字来源于德语'kobold'，意为'小精灵'或'恶魔'，因为矿工们发现含钴矿石难以冶炼且常伴有有毒的砷烟。钴化合物长期被用作蓝色颜料，如著名的'钴蓝'，在中国的青花瓷中也有广泛应用。"
    },
    {
        number: 28,
        symbol: "Ni",
        name: "Nickel",
        chineseName: "镍",
        weight: "58.693",
        category: "transition-metal",
        group: 10, 
        period: 4,
        discoverer: "阿克塞尔·弗雷德里克·克朗斯泰特",
        year: "1751",
        story: "1751年，瑞典矿物学家克朗斯泰特从矿石中分离出了镍。'镍'(Nickel)这个名字来源于德语'kupfernickel'，意为'淘气的铜精灵'，因为矿工们发现这种红色矿石看似含铜却无法提取铜。镍被广泛用于硬币制造、不锈钢生产和电池制造。"
    },
    {
        number: 29,
        symbol: "Cu",
        name: "Copper",
        chineseName: "铜",
        weight: "63.546",
        category: "transition-metal",
        group: 11, 
        period: 4,
        discoverer: "古代已知",
        year: "古代",
        story: "铜是人类使用的最早金属之一，早在公元前9000年就有证据表明人类开始使用天然铜。铜的冶炼技术约在公元前5000年发展起来，标志着铜器时代的开始。'铜'(Copper)这个名字来源于拉丁语'cuprum'，源自塞浦路斯岛(Cyprus)，古代著名的铜产地。铜的发现和使用对人类文明的发展起到了关键作用。"
    },
    {
        number: 30,
        symbol: "Zn",
        name: "Zinc",
        chineseName: "锌",
        weight: "65.38",
        category: "transition-metal",
        group: 12, 
        period: 4,
        discoverer: "安德烈亚斯·西格蒙德·马格拉夫",
        year: "1746",
        story: "虽然锌合金(如黄铜)自古以来就被使用，但金属锌的分离和识别直到18世纪才实现。1746年，德国化学家马格拉夫首次确认锌是一种独特的金属。'锌'(Zinc)这个名字可能来源于德语'zink'，与'尖齿'有关，因为锌结晶时形成尖锐的形状。锌在人体中是必需的微量元素，对免疫系统、伤口愈合和DNA合成至关重要。"
    },
    {
        number: 31,
        symbol: "Ga",
        name: "Gallium",
        chineseName: "镓",
        weight: "69.723",
        category: "post-transition-metal",
        group: 13, 
        period: 4,
        discoverer: "保罗·埃米尔·勒科克·德·布瓦博德兰",
        year: "1875",
        story: "1875年，法国化学家勒科克通过分析锌矿中的杂质发现了镓。有趣的是，镓的存在和性质早在1871年就被门捷列夫预言，他称之为'埃卡铝'。'镓'(Gallium)这个名字来源于拉丁语'Gallia'，即法国的古称。镓的熔点极低(约30°C)，可以在手中融化，但沸点却很高，这种特性使它成为测温计和高温温度计的理想材料。"
    },
    {
        number: 32,
        symbol: "Ge",
        name: "Germanium",
        chineseName: "锗",
        weight: "72.630",
        category: "metalloid",
        group: 14, 
        period: 4,
        discoverer: "克莱门斯·温克勒",
        year: "1886",
        story: "1886年，德国化学家温克勒在分析一种名为辉银矿的矿物时发现了锗。有趣的是，锗的存在和性质在1871年就被门捷列夫所预言，当时他称之为'埃卡硅'。'锗'(Germanium)这个名字来源于拉丁语'Germania'，即德国的古称。锗是第一个证实门捷列夫周期表预测准确性的元素，在半导体工业发展初期起到了重要作用。"
    },
    {
        number: 33,
        symbol: "As",
        name: "Arsenic",
        chineseName: "砷",
        weight: "74.922",
        category: "metalloid",
        group: 15, 
        period: 4,
        discoverer: "古代已知",
        year: "古代",
        story: "砷化合物自古以来就为人所知，古希腊和罗马人了解砷的硫化物（雄黄和雌黄）。砷元素在13世纪由炼金术士阿尔贝图斯·马格努斯首次分离出来。'砷'(Arsenic)这个名字可能来源于波斯语'زرنيخ' (zarnikh)，意为'黄色色素'。砷曾被用作颜料、药物和毒药，有'毒药之王'的称号。历史上，拿破仑的死亡就与砷中毒有关。"
    },
    {
        number: 34,
        symbol: "Se",
        name: "Selenium",
        chineseName: "硒",
        weight: "78.971",
        category: "nonmetal",
        group: 16, 
        period: 4,
        discoverer: "延斯·雅各布·贝采利乌斯",
        year: "1817",
        story: "1817年，瑞典化学家贝采利乌斯在制硫酸的铅室工艺中发现了一种新元素。他将其命名为'硒'(Selenium)，来源于希腊语'selene'，意为'月亮'，与之前发现的碲(tellus，地球)相对应。硒最初被认为有毒，但后来发现它是人体必需的微量元素，对免疫系统功能和抗氧化保护至关重要。"
    },
    {
        number: 35,
        symbol: "Br",
        name: "Bromine",
        chineseName: "溴",
        weight: "79.904",
        category: "nonmetal",
        group: 17, 
        period: 4,
        discoverer: "安托万·杰罗姆·巴拉尔",
        year: "1826",
        story: "1826年，法国化学家巴拉尔从海水中分离出了溴。几乎同时，德国化学家利比希也独立发现了溴。'溴'(Bromine)这个名字来源于希腊语'bromos'，意为'恶臭'，因为溴是唯一在室温下呈液态的非金属元素，且散发出刺鼻的红棕色蒸气。溴曾被用作摄影材料、阻燃剂和汽油添加剂。"
    },
    {
        number: 36,
        symbol: "Kr",
        name: "Krypton",
        chineseName: "氪",
        weight: "83.798",
        category: "noble-gas",
        group: 18, 
        period: 4,
        discoverer: "威廉·拉姆齐和莫里斯·特拉沃斯",
        year: "1898",
        story: "1898年，英国科学家拉姆齐和特拉沃斯在研究液态空气时发现了氪。'氪'(Krypton)这个名字来源于希腊语'kryptos'，意为'隐藏的'，因为这种稀有气体在空气中的含量极低，难以被发现。氪被用于高强度闪光灯、特殊照明和激光技术。在超级英雄故事中，'氪星'是超人的家乡，而'氪石'是能使超人虚弱的神秘物质。"
    },
    {
        number: 37,
        symbol: "Rb",
        name: "Rubidium",
        chineseName: "铷",
        weight: "85.468",
        category: "alkali-metal",
        group: 1, 
        period: 5,
        discoverer: "罗伯特·威廉·本森和古斯塔夫·基尔霍夫",
        year: "1861",
        story: "1861年，德国科学家本森和基尔霍夫使用当时刚发明的光谱分析法，在矿泉水中发现了铷。'铷'(Rubidium)这个名字来源于拉丁语'rubidus'，意为'深红色'，因为它的光谱线呈深红色。铷是一种极活泼的碱金属，会在空气中自燃，与水反应剧烈。铷的放射性同位素被用于医学成像和神经科学研究。"
    },
    {
        number: 38,
        symbol: "Sr",
        name: "Strontium",
        chineseName: "锶",
        weight: "87.62",
        category: "alkaline-earth",
        group: 2, 
        period: 5,
        discoverer: "阿德尔·克劳福德",
        year: "1790",
        story: "1790年，苏格兰医生克劳福德在苏格兰小镇斯特朗蒂安附近的铅矿中发现了一种新矿物。1808年，戴维通过电解成功分离出金属锶。'锶'(Strontium)这个名字来源于斯特朗蒂安(Strontian)这个地名。锶化合物产生鲜艳的红色火焰，被广泛用于烟火制造。锶-90是核试验的主要放射性产物之一，而锶-89和锶-90被用于癌症治疗。"
    },
    {
        number: 39,
        symbol: "Y",
        name: "Yttrium",
        chineseName: "钇",
        weight: "88.906",
        category: "transition-metal",
        group: 3, 
        period: 5,
        discoverer: "约翰·加多林",
        year: "1794",
        story: "1794年，芬兰化学家加多林在瑞典小镇于特比附近发现了一种新矿物，后来被命名为钆土。1828年，德国化学家沃勒从中分离出了钇的氧化物。'钇'(Yttrium)这个名字来源于瑞典小镇于特比(Ytterby)，这个小镇因为有四种元素以它命名而闻名：钇、铒、铽和镱。钇被用于制造红色荧光粉、高温超导体和特种合金。"
    },
    {
        number: 40,
        symbol: "Zr",
        name: "Zirconium",
        chineseName: "锆",
        weight: "91.224",
        category: "transition-metal",
        group: 4, 
        period: 5,
        discoverer: "马丁·海因里希·克拉普罗特",
        year: "1789",
        story: "1789年，德国化学家克拉普罗特在分析锆石矿物时发现了锆的氧化物。1824年，瑞典化学家贝采利乌斯首次分离出不纯的锆金属。'锆'(Zirconium)这个名字来源于阿拉伯语'zargun'，意为'金色'，因为锆的某些矿物呈金色。锆以其出色的耐腐蚀性和耐高温性而闻名，被广泛用于核反应堆、化工设备和假牙等医疗植入物。"
    },
    {
        number: 41,
        symbol: "Nb",
        name: "Niobium",
        chineseName: "铌",
        weight: "92.906",
        category: "transition-metal",
        group: 5, 
        period: 5,
        discoverer: "查尔斯·哈切特",
        year: "1801",
        story: "1801年，英国化学家哈切特在一块来自美国的矿物样本中发现了一种新元素，最初命名为'钶'。1844年，德国化学家罗斯证明钶实际上包含两种元素，他将其中一种命名为'铌'(Niobium)，源自希腊神话中的人物尼俄柏(Niobe)，另一种命名为'钽'。铌具有优异的超导性能，被用于制造超导磁体、特殊钢合金和航空航天材料。"
    },
    {
        number: 42,
        symbol: "Mo",
        name: "Molybdenum",
        chineseName: "钼",
        weight: "95.95",
        category: "transition-metal",
        group: 6, 
        period: 5,
        discoverer: "卡尔·威廉·舍勒",
        year: "1778",
        story: "虽然钼的化合物自古以来就被误认为是铅矿，但直到1778年，瑞典化学家舍勒才证明钼辉石含有一种全新的元素。1781年，他成功分离出了钼的氧化物。'钼'(Molybdenum)这个名字来源于希腊语'molybdos'，意为'铅'，因为其矿物与铅矿相似。钼是人体必需的微量元素，用于某些酶的活性。在工业上，钼被广泛用于制造高强度钢合金和催化剂。"
    },
    {
        number: 43,
        symbol: "Tc",
        name: "Technetium",
        chineseName: "锝",
        weight: "98",
        category: "transition-metal",
        group: 7, 
        period: 5,
        discoverer: "卡洛·佩里尔和埃米利奥·塞格雷",
        year: "1937",
        story: "锝是第一个人工合成的元素，1937年由意大利科学家佩里尔和塞格雷在美国伯克利实验室用回旋加速器轰击钼靶制得。'锝'(Technetium)这个名字来源于希腊语'technetos'，意为'人工的'。有趣的是，门捷列夫曾预言这种元素的存在，称之为'埃卡锰'。锝没有稳定同位素，所有同位素都具有放射性。锝-99m广泛用于医学诊断，是核医学中最常用的放射性核素。"
    },
    {
        number: 44,
        symbol: "Ru",
        name: "Ruthenium",
        chineseName: "钌",
        weight: "101.07",
        category: "transition-metal",
        group: 8, 
        period: 5,
        discoverer: "卡尔·克劳斯",
        year: "1844",
        story: "1844年，俄国化学家克劳斯在铂矿中分离出了钌。'钌'(Ruthenium)这个名字来源于拉丁语'Ruthenia'，即俄罗斯的古称，克劳斯以此向祖国致敬。钌是一种罕见的铂族金属，具有出色的耐腐蚀性和硬度。它被用于电子接点、硬盘涂层和高性能催化剂。钌化合物也被研究用于癌症治疗。"
    },
    {
        number: 45,
        symbol: "Rh",
        name: "Rhodium",
        chineseName: "铑",
        weight: "102.91",
        category: "transition-metal",
        group: 9, 
        period: 5,
        discoverer: "威廉·海德·沃拉斯顿",
        year: "1804",
        story: "1804年，英国化学家沃拉斯顿在粗铂矿中发现了铑。'铑'(Rhodium)这个名字来源于希腊语'rhodon'，意为'玫瑰'，因为铑的某些盐溶液呈玫瑰红色。铑是世界上最稀有和最昂贵的金属之一，具有出色的反射率和耐腐蚀性。它主要用作汽车尾气催化转换器的催化剂，也用于珠宝镀层和特殊的反射镜面。"
    },
    {
        number: 46,
        symbol: "Pd",
        name: "Palladium",
        chineseName: "钯",
        weight: "106.42",
        category: "transition-metal",
        group: 10, 
        period: 5,
        discoverer: "威廉·海德·沃拉斯顿",
        year: "1803",
        story: "1803年，英国化学家沃拉斯顿在提纯铂时发现了钯。'钯'(Palladium)这个名字来源于当时新发现的小行星帕拉斯(Pallas)，而后者又是以希腊智慧女神雅典娜的别名命名的。钯是铂族金属中最活泼的一种，能吸收大量的氢气。它主要用于汽车催化转换器、电子设备、牙科合金和珠宝制造。在氢能源研究中，钯作为储氢材料也备受关注。"
    },
    {
        number: 47,
        symbol: "Ag",
        name: "Silver",
        chineseName: "银",
        weight: "107.87",
        category: "transition-metal",
        group: 11, 
        period: 5,
        discoverer: "古代已知",
        year: "古代",
        story: "银自古以来就被人类用于制作装饰品和货币，至少可以追溯到公元前5000年。'银'(Silver)这个名字来源于盎格鲁-撒克逊语'seolfor'。银因其高反射率和导电性而闻名，也是唯一一种能够反射所有可见光波长的金属，使其成为制作镜子的理想材料。",
        imageUrl: "https://images.unsplash.com/photo-1609093578825-38ac8a2ca8af?w=600&auto=format&fit=crop"
    },
    {
        number: 48,
        symbol: "Cd",
        name: "Cadmium",
        chineseName: "镉",
        weight: "112.41",
        category: "transition-metal",
        group: 12, 
        period: 5,
        discoverer: "弗里德里希·施特罗迈尔",
        year: "1817",
        story: "1817年，德国医生和化学家施特罗迈尔在分析碳酸锌中的杂质时发现了镉。'镉'(Cadmium)这个名字来源于拉丁语'cadmia'和希腊语'kadmeia'，意为'锌矿石'。镉以其毒性而闻名，曾经引发日本的'痛痛病'公共卫生危机。尽管如此，镉仍被用于镍镉电池、防腐涂层和某些合金。由于环保考虑，许多国家正逐步减少和禁止镉的使用。"
    },
    {
        number: 49,
        symbol: "In",
        name: "Indium",
        chineseName: "铟",
        weight: "114.82",
        category: "post-transition-metal",
        group: 13, 
        period: 5,
        discoverer: "费迪南德·赖希和希奥多尔·里希特",
        year: "1863",
        story: "1863年，德国科学家赖希和里希特在分析锌矿石时使用光谱分析发现了铟。'铟'(Indium)这个名字来源于其光谱中的特征靛蓝色线，拉丁语'indicum'意为'靛蓝'。铟是一种柔软的银白色金属，熔点低，在手中可以留下痕迹。现代，铟主要用于制造液晶显示屏的透明导电涂层(ITO)，也用于半导体和低熔点合金。"
    },
    {
        number: 50,
        symbol: "Sn",
        name: "Tin",
        chineseName: "锡",
        weight: "118.71",
        category: "post-transition-metal",
        group: 14, 
        period: 5,
        discoverer: "古代已知",
        year: "古代",
        story: "锡是人类最早使用的金属之一，早在公元前3500年就被用于与铜合金制造青铜。'锡'(Tin)这个名字来源于古英语'tin'。古代文明就已经发现了锡的重要性，青铜的发明开创了青铜时代。锡具有低毒性、易熔性和较好的耐腐蚀性，历史上广泛用于食物容器制造。现代，锡被用于焊料、锡箔、防腐涂层和各种合金。有趣的是，锡在低温下会发生'锡病'，变成粉末状。"
    },
    {
        number: 51,
        symbol: "Sb",
        name: "Antimony",
        chineseName: "锑",
        weight: "121.76",
        category: "metalloid",
        group: 15, 
        period: 5,
        discoverer: "古代已知",
        year: "古代",
        story: "锑的化合物自古以来就被用作化妆品和药物。古埃及人已经使用硫化锑作为眼线膏。元素锑在中世纪由炼金术士分离出来。'锑'(Antimony)这个名字可能来源于希腊语'anti-monos'，意为'不单独的'，因为它很少以纯形式存在。锑有多种同素异形体，具有半导体性质。现代，锑主要用于阻燃剂、蓄电池、合金和半导体材料。"
    },
    {
        number: 52,
        symbol: "Te",
        name: "Tellurium",
        chineseName: "碲",
        weight: "127.60",
        category: "metalloid",
        group: 16, 
        period: 5,
        discoverer: "弗朗茨·约瑟夫·米勒",
        year: "1782",
        story: "1782年，匈牙利矿物学家米勒从金矿中分离出了碲。'碲'(Tellurium)这个名字来源于拉丁语'tellus'，意为'地球'。碲是一种罕见的元素，具有金属光泽但性质介于金属和非金属之间。在人体中，碲代谢后会产生有大蒜气味的化合物，使皮肤和呼吸带有特殊气味，科学家称之为'碲的诅咒'。现代，碲主要用于半导体、光电材料和某些合金的添加剂。"
    },
    {
        number: 53,
        symbol: "I",
        name: "Iodine",
        chineseName: "碘",
        weight: "126.90",
        category: "nonmetal",
        group: 17, 
        period: 5,
        discoverer: "贝尔纳·库尔图瓦",
        year: "1811",
        story: "1811年，法国化学家库尔图瓦在制碱过程中意外发现了碘。他注意到加热海藻灰时产生的紫色蒸气会凝结成黑色晶体。'碘'(Iodine)这个名字来源于希腊语'iodes'，意为'紫色的'，描述了其蒸气的颜色。碘是人体必需的微量元素，是甲状腺激素的重要组成部分。缺碘会导致甲状腺肿大和智力障碍。因此，许多国家在食盐中添加碘化物以预防缺碘症。"
    },
    {
        number: 54,
        symbol: "Xe",
        name: "Xenon",
        chineseName: "氙",
        weight: "131.29",
        category: "noble-gas",
        group: 18, 
        period: 5,
        discoverer: "威廉·拉姆齐和莫里斯·特拉沃斯",
        year: "1898",
        story: "1898年，英国科学家拉姆齐和特拉沃斯在研究液态空气时发现了氙。'氙'(Xenon)这个名字来源于希腊语'xenos'，意为'陌生的'或'外来的'。虽然氙是惰性气体，但它能与氟等强氧化剂形成化合物，成为第一个被证明能形成化合物的惰性气体。氙被用于高强度灯泡、闪光灯、激光和麻醉剂。由于其惰性特性，氙也被用作离子推进器的推进剂。"
    },
    {
        number: 55,
        symbol: "Cs",
        name: "Caesium",
        chineseName: "铯",
        weight: "132.91",
        category: "alkali-metal",
        group: 1, 
        period: 6,
        discoverer: "罗伯特·本森和古斯塔夫·基尔霍夫",
        year: "1860",
        story: "1860年，德国科学家本森和基尔霍夫通过光谱分析在矿泉水中发现了铯。'铯'(Caesium)这个名字来源于拉丁语'caesius'，意为'天蓝色'，描述了其光谱中的特征蓝线。铯是已知的最活泼金属，在空气中会自燃，与水反应极其剧烈。它的熔点极低，仅为28.5°C，几乎可以在手中融化。铯被用于原子钟，提供了极其精确的时间测量，对GPS系统等技术至关重要。"
    },
    {
        number: 56,
        symbol: "Ba",
        name: "Barium",
        chineseName: "钡",
        weight: "137.33",
        category: "alkaline-earth",
        group: 2, 
        period: 6,
        discoverer: "汉弗莱·戴维",
        year: "1808",
        story: "虽然钡的化合物早在1602年就被发现，但钡元素直到1808年才被英国化学家戴维通过电解分离出来。'钡'(Barium)这个名字来源于希腊语'barys'，意为'重的'，因为其化合物重晶石比普通岩石重得多。钡的化合物能吸收X射线，因此硫酸钡被用作'钡餐'，帮助医生在X光下观察消化系统。纯钡是有毒的，但其硫酸盐由于极不溶于水而相对安全。"
    },
    {
        number: 57,
        symbol: "La",
        name: "Lanthanum",
        chineseName: "镧",
        weight: "138.91",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "卡尔·莫桑德",
        year: "1839",
        story: "1839年，瑞典化学家莫桑德从氧化铈中分离出了镧。'镧'(Lanthanum)这个名字来源于希腊语'lanthanein'，意为'隐藏的'，因为它在铈矿中'隐藏'了很长时间。镧开启了稀土元素家族——镧系元素，这些元素在现代技术中发挥着关键作用。镧被用于高折射率光学玻璃、混合金属储氢材料和特种合金。镧化合物也被用作催化剂和在炼油工业中。"
    },
    {
        number: 58,
        symbol: "Ce",
        name: "Cerium",
        chineseName: "铈",
        weight: "140.12",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "延斯·雅各布·贝采利乌斯和威廉·希辛格尔",
        year: "1803",
        story: "1803年，瑞典化学家贝采利乌斯和希辛格尔以及德国化学家克拉普罗特几乎同时发现了铈。'铈'(Cerium)这个名字来源于当时新发现的小行星谷神星(Ceres)，而后者又是以罗马农业女神命名的。铈是最丰富的稀土元素，在地壳中的含量甚至超过铜和锡。铈的化合物在玻璃抛光、催化转换器和自清洁烤箱中有重要应用。铈还被用作打火石的成分，因为铈铁合金在摩擦时会产生火花。"
    },
    {
        number: 59,
        symbol: "Pr",
        name: "Praseodymium",
        chineseName: "镨",
        weight: "140.91",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "卡尔·奥尔·冯·韦尔斯巴赫",
        year: "1885",
        story: "1885年，奥地利化学家冯·韦尔斯巴赫将'老镝'(didymium)分离成两种元素：镨和钕。'镨'(Praseodymium)这个名字来源于希腊语'prasios didymos'，意为'绿色的双胞胎'，描述了其盐溶液的绿色。镨被用于制造特种玻璃、陶瓷和永磁体。镨与钕的混合物给特殊眼镜(如熔接护目镜)提供保护性能，能阻挡强烈的黄光。镨化合物创造出亮丽的黄绿色，被用于彩色玻璃和珐琅。"
    },
    {
        number: 60,
        symbol: "Nd",
        name: "Neodymium",
        chineseName: "钕",
        weight: "144.24",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "卡尔·奥尔·冯·韦尔斯巴赫",
        year: "1885",
        story: "1885年，奥地利化学家冯·韦尔斯巴赫在同一实验中发现了镨和钕。'钕'(Neodymium)这个名字来源于希腊语'neos didymos'，意为'新的双胞胎'。钕是现代技术中最重要的稀土元素之一，主要用于制造强力永磁体(钕铁硼磁体)，这种磁体被广泛应用于硬盘驱动器、耳机、扬声器和风力发电机。钕还被用于制造激光材料和彩色玻璃。钕玻璃能滤除黄光，因此天文望远镜中常使用钕滤光片以提高图像对比度。"
    },
    {
        number: 61,
        symbol: "Pm",
        name: "Promethium",
        chineseName: "钷",
        weight: "145",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "杰克·马里斯基、劳伦斯·格伦丹宁和查尔斯·科赖尔",
        year: "1945",
        story: "钷是唯一一种在自然界中不存在的稀土元素，所有钷同位素都是放射性的。1945年，美国科学家马里斯基、格伦丹宁和科赖尔在橡树岭国家实验室通过铀核裂变产物中首次分离出钷。'钷'(Promethium)这个名字来源于希腊神话中的人物普罗米修斯(Prometheus)，他偷火给人类。钷可以通过核反应生产，主要用于手表、仪表和航天器上的自发光源，也用于原子电池。钷在医学上也有应用，如用于治疗视网膜脱离。"
    },
    {
        number: 62,
        symbol: "Sm",
        name: "Samarium",
        chineseName: "钐",
        weight: "150.36",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "保罗·埃米尔·勒科克·德·布瓦博德兰",
        year: "1879",
        story: "1879年，法国化学家勒科克在从矿物中分离稀土元素的过程中发现了钐。'钐'(Samarium)这个名字来源于矿物绿柱石(samarskite)，而后者是以俄国矿物学家萨马尔斯基(Samarsky)命名的。钐被用于制造强力钐钴永磁体，这种磁体在20世纪70年代之前是最强的永磁体。钐还被用于光学玻璃、激光材料和核反应堆的中子吸收剂。钐的一个同位素钐-153被用于缓解癌症骨转移引起的疼痛。"
    },
    {
        number: 63,
        symbol: "Eu",
        name: "Europium",
        chineseName: "铕",
        weight: "151.96",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "欧仁·安塔万·德马尔塞",
        year: "1901",
        story: "1901年，法国化学家德马尔塞通过分离钐盐发现了铕。'铕'(Europium)这个名字来源于欧洲(Europe)大陆。铕是一种相对罕见的稀土元素，具有强烈的荧光性质。铕化合物产生红色荧光，被广泛用于彩色电视和电脑显示器中。铕还被用于防伪技术，如欧元纸币中的荧光材料。铕是制造三基色荧光灯中的红色荧光粉的关键成分，使照明更加节能。"
    },
    {
        number: 64,
        symbol: "Gd",
        name: "Gadolinium",
        chineseName: "钆",
        weight: "157.25",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "让·夏尔·加利萨尔·德·马里尼亚克",
        year: "1880",
        story: "1880年，瑞士化学家马里尼亚克通过分光分析法发现了钆。'钆'(Gadolinium)这个名字来源于芬兰化学家加多林(Gadolin)，他发现了第一块含稀土元素的矿石。钆具有独特的磁性和热性质，是已知的室温下最强的顺磁性元素。钆被用于磁共振成像(MRI)造影剂，帮助医生获得更清晰的图像。钆还被用于制造特殊合金、电子元件和核反应堆的控制棒。"
    },
    {
        number: 65,
        symbol: "Tb",
        name: "Terbium",
        chineseName: "铽",
        weight: "158.93",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "卡尔·古斯塔夫·莫桑德",
        year: "1843",
        story: "1843年，瑞典化学家莫桑德在稀土混合物中发现了铽。'铽'(Terbium)这个名字来源于瑞典小镇于特比(Ytterby)，那里发现了含有多种稀土元素的矿物。铽化合物能发出强烈的绿色荧光，被用于制造荧光灯、彩色电视显像管和X射线增强屏。铽还被用于某些永磁材料、声光设备和磁致伸缩材料。铽与铁组成的合金具有巨大的磁致伸缩性能，被用于海军声纳系统和精密定位装置。"
    },
    {
        number: 66,
        symbol: "Dy",
        name: "Dysprosium",
        chineseName: "镝",
        weight: "162.50",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "保罗·埃米尔·勒科克·德·布瓦博德兰",
        year: "1886",
        story: "1886年，法国化学家勒科克在分析钬样品时发现了镝。'镝'(Dysprosium)这个名字来源于希腊语'dysprositos'，意为'难以接近的'，因为镝很难从其他稀土元素中分离出来。镝具有极强的磁性，被用于制造高性能永磁体，特别是需要在高温下工作的磁体。镝还被用于核反应堆控制棒、特种光学材料和某些金属卤化物灯。随着电动汽车和风力发电机的普及，镝的需求急剧增加。"
    },
    {
        number: 67,
        symbol: "Ho",
        name: "Holmium",
        chineseName: "钬",
        weight: "164.93",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "马克·德拉丰丹和雅克·路易·苏雷",
        year: "1878",
        story: "1878年，瑞典化学家克莱夫和瑞士化学家德拉丰丹几乎同时独立发现了钬。'钬'(Holmium)这个名字来源于斯德哥尔摩的拉丁文名Holmia。钬的化合物呈现出独特的粉红色或黄色，其光谱有一系列锐利的吸收线，是已知元素中最具特色的。钬具有极强的磁性，被用于制造强磁场磁体。钬激光在医学上有重要应用，特别是在眼科手术中。钬还被用于核反应堆控制棒和特种光纤。"
    },
    {
        number: 68,
        symbol: "Er",
        name: "Erbium",
        chineseName: "铒",
        weight: "167.26",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "卡尔·古斯塔夫·莫桑德",
        year: "1843",
        story: "1843年，瑞典化学家莫桑德在钇矿中发现了铒。'铒'(Erbium)这个名字同样来源于瑞典小镇于特比(Ytterby)。铒化合物呈现出美丽的粉红色，是粉红色玻璃和陶瓷的着色剂。铒最重要的应用是在光纤通信中，掺铒光纤放大器(EDFA)大大提高了长距离光纤通信的效率，是互联网快速发展的关键技术之一。铒激光在医学领域也有重要应用，如皮肤治疗和牙科手术。"
    },
    {
        number: 69,
        symbol: "Tm",
        name: "Thulium",
        chineseName: "铥",
        weight: "168.93",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "佩尔·特奥多尔·克莱夫",
        year: "1879",
        story: "1879年，瑞典化学家克莱夫在研究铒矿物时发现了铥。'铥'(Thulium)这个名字来源于古北欧神话中的北方之地图勒(Thule)。铥是所有天然存在的稀土元素中最稀少的一种，比铂还要罕见。铥具有荧光性质，被用于便携式X射线设备、特种激光和某些荧光材料。铥-170同位素被用作辐射源，在医疗便携式X射线设备和非破坏性检测中有应用。铥化合物在某些高温超导体研究中也很重要。"
    },
    {
        number: 70,
        symbol: "Yb",
        name: "Ytterbium",
        chineseName: "镱",
        weight: "173.05",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "让·夏尔·加利萨尔·德·马里尼亚克",
        year: "1878",
        story: "1878年，瑞士化学家马里尼亚克在研究铒氧化物时发现了镱。'镱'(Ytterbium)这个名字同样来源于瑞典小镇于特比(Ytterby)。镱是一种相对软的银白色金属，在空气中会慢慢氧化。镱有不寻常的物理性质，如在压力下电阻会显著增加。镱被用于特种合金、光纤激光器和某些光学材料。镱钟是一种极其精确的原子钟，精确度可达四千亿分之一秒，有助于研究基础物理定律和开发更精确的导航系统。"
    },
    {
        number: 71,
        symbol: "Lu",
        name: "Lutetium",
        chineseName: "镥",
        weight: "174.97",
        category: "lanthanide",
        group: 3, 
        period: 6,
        discoverer: "乔治·乌尔班",
        year: "1907",
        story: "1907年，法国科学家乌尔班和奥地利矿物学家冯·韦尔斯巴赫几乎同时独立发现了镥。'镥'(Lutetium)这个名字来源于巴黎的罗马时期名称Lutetia。镥是镧系元素中最重的一个，也是最难分离的稀土元素之一。镥具有独特的催化性能，被用于石油裂化催化剂。镥-176同位素被用于确定陨石年龄。镥还被用于正电子发射断层扫描(PET)放射性示踪剂和某些特种玻璃。虽然镥很稀有，但其应用在医学和石油化工领域十分重要。"
    },
    {
        number: 72,
        symbol: "Hf",
        name: "Hafnium",
        chineseName: "铪",
        weight: "178.49",
        category: "transition-metal",
        group: 4, 
        period: 6,
        discoverer: "迪尔克·科斯特和乔治·查尔斯·冯·赫维西",
        year: "1923",
        story: "1923年，荷兰物理学家科斯特和匈牙利化学家冯·赫维西通过X射线光谱学在锆矿中发现了铪。'铪'(Hafnium)这个名字来源于哥本哈根的拉丁文名Hafnia。铪和锆的化学性质极为相似，在自然界中总是共同存在，这使得铪的发现比较困难。铪具有极高的中子吸收截面，被广泛用于核反应堆控制棒。铪还由于其高熔点和优良的机械性能，被用于等离子火箭喷嘴、超合金和某些电子设备。在半导体工业中，铪氧化物被用作高介电常数材料，有助于开发更小的晶体管。"
    },
    {
        number: 73,
        symbol: "Ta",
        name: "Tantalum",
        chineseName: "钽",
        weight: "180.95",
        category: "transition-metal",
        group: 5, 
        period: 6,
        discoverer: "安德斯·古斯塔夫·埃克伯格",
        year: "1802",
        story: "1802年，瑞典化学家埃克伯格在分析矿物样本时发现了钽，但直到1844年才被明确区分于铌。'钽'(Tantalum)这个名字来源于希腊神话中的人物坦塔罗斯(Tantalus)，象征它在酸中'不可溶解'的特性，就像坦塔罗斯不能喝到周围的水一样。钽具有极强的耐腐蚀性和生物相容性，被广泛用于电子电容器、医疗植入物(如人工关节和骨板)和化学工业设备。钽电容器因其高可靠性和小体积，成为手机、电脑等小型电子设备的关键组件。"
    },
    {
        number: 74,
        symbol: "W",
        name: "Tungsten",
        chineseName: "钨",
        weight: "183.84",
        category: "transition-metal",
        group: 6, 
        period: 6,
        discoverer: "卡尔·威廉·舍勒",
        year: "1783",
        story: "1783年，瑞典化学家舍勒从矿物中分离出了钨酸，但直到1783年，西班牙化学家兄弟胡安·何塞和费乌斯托·德埃卢亚尔才成功分离出金属钨。'钨'(Tungsten)一词来源于瑞典语'tung sten'，意为'重石'，而元素符号W则来自其德语名称'Wolfram'。钨以其极高的熔点(3422°C)而著称，是所有金属中熔点最高的。钨主要用于灯丝、焊接、切削工具和穿甲弹。碳化钨是极其坚硬的材料，广泛用于钻头、刀具和装甲钢。"
    },
    {
        number: 75,
        symbol: "Re",
        name: "Rhenium",
        chineseName: "铼",
        weight: "186.21",
        category: "transition-metal",
        group: 7, 
        period: 6,
        discoverer: "瓦尔特·诺达克、伊达·诺达克和奥托·伯格",
        year: "1925",
        story: "1925年，德国科学家夫妇诺达克和伯格在处理铂矿和钽矿样品时发现了铼。'铼'(Rhenium)这个名字来源于莱茵河(Rhine)的拉丁文名称Rhenus。铼是最后一个被发现的稳定天然元素。铼具有极高的熔点(3186°C)，仅次于钨和碳，以及优良的耐磨性和耐腐蚀性。铼主要用于高温合金，特别是喷气发动机涡轮叶片。铼还被用作催化剂，特别是在石油精炼过程中用于生产高辛烷值汽油。由于其稀有性和关键应用，铼被视为战略资源。"
    },
    {
        number: 76,
        symbol: "Os",
        name: "Osmium",
        chineseName: "锇",
        weight: "190.23",
        category: "transition-metal",
        group: 8, 
        period: 6,
        discoverer: "史密森·坦南特",
        year: "1803",
        story: "1803年，英国化学家坦南特在研究铂矿时发现了锇和铱。'锇'(Osmium)这个名字来源于希腊语'osme'，意为'气味'，因为锇的四氧化物有强烈的刺鼻气味。锇是已知自然元素中密度最大的(22.59 g/cm³)，比铂或铱还要重。锇极难融化，熔点高达3033°C。锇主要用于硬质合金、电子接点和高端钢笔笔尖。锇的最重要用途是与铱、铂等制成合金，用于承受极端条件的设备部件。锇化合物也被用作生物染色剂和催化剂。"
    },
    {
        number: 77,
        symbol: "Ir",
        name: "Iridium",
        chineseName: "铱",
        weight: "192.22",
        category: "transition-metal",
        group: 9, 
        period: 6,
        discoverer: "史密森·坦南特",
        year: "1803",
        story: "1803年，英国化学家坦南特在同一实验中发现了铱和锇。'铱'(Iridium)这个名字来源于希腊神话中的彩虹女神伊里斯(Iris)，因为铱的盐溶液呈现各种颜色。铱是一种极其坚硬、耐腐蚀的贵金属，是已知最抗腐蚀的元素。铱被用于电触点、火花塞电极和特殊的坩埚。国际千克原器就是铱铂合金制成的。有趣的是，地球表面铱含量很低，但在白垩纪-第三纪界线处发现了铱异常富集，这成为小行星撞击导致恐龙灭绝理论的重要证据。"
    },
    {
        number: 78,
        symbol: "Pt",
        name: "Platinum",
        chineseName: "铂",
        weight: "195.08",
        category: "transition-metal",
        group: 10, 
        period: 6,
        discoverer: "安东尼奥·德·乌洛亚",
        year: "1735",
        story: "铂早在公元前700年就被古埃及人使用，但作为一种独特的金属直到1735年才被西班牙科学家乌洛亚在南美洲的金矿中正式发现。'铂'(Platinum)这个名字来源于西班牙语'platina'，意为'小银'。铂以其稀有性、耐腐蚀性和催化性能而闻名。铂是珠宝、催化转换器、实验室器具和电子设备的重要材料。在化学工业中，铂催化剂在许多重要反应中不可或缺。在医学上，含铂化合物如顺铂是治疗癌症的重要药物。"
    },
    {
        number: 79,
        symbol: "Au",
        name: "Gold",
        chineseName: "金",
        weight: "196.97",
        category: "transition-metal",
        group: 11, 
        period: 6,
        discoverer: "古代已知",
        year: "古代",
        story: "金是人类最早认识和使用的金属之一，至少从公元前4000年就开始被用于装饰和货币。'金'(Gold)这个名字来源于古英语'geolu'，意为'黄色'，而元素符号Au来自拉丁语'aurum'。金因其美丽的黄色光泽、稀有性、可锻性和耐腐蚀性而受到珍视。金主要用于珠宝、投资和电子工业。金是极好的导体，不会氧化，因此在高端电子设备中被用作连接器和电路。在医学上，金化合物被用于治疗类风湿性关节炎，而放射性金同位素用于癌症治疗。",
        imageUrl: "https://images.unsplash.com/photo-1610375461246-83df859d849d?w=600&auto=format&fit=crop"
    },
    {
        number: 80,
        symbol: "Hg",
        name: "Mercury",
        chineseName: "汞",
        weight: "200.59",
        category: "transition-metal",
        group: 12, 
        period: 6,
        discoverer: "古代已知",
        year: "古代",
        story: "汞自古以来就为人所知，早在公元前2000年的古埃及墓葬中就发现了含汞的物品。'汞'(Mercury)这个名字来源于罗马神话中的信使神墨丘利，象征其活泼流动的特性，而元素符号Hg来自拉丁语'hydrargyrum'，意为'水银'。汞是唯一在常温下呈液态的金属元素。历史上，汞被用于温度计、气压计、开关和牙科汞合金。然而，由于其毒性，许多这些用途现已被淘汰。汞化合物曾被用作药物和防腐剂，但同样因毒性问题而被替代。著名的'疯帽匠'形象来源于19世纪制帽工人因长期接触汞而出现的汞中毒症状。"
    },
    {
        number: 82,
        symbol: "Pb",
        name: "Lead",
        chineseName: "铅",
        weight: "207.2",
        category: "post-transition-metal",
        group: 14, 
        period: 6,
        discoverer: "古代已知",
        year: "古代",
        story: "铅是最早被人类使用的金属之一，古埃及人早在公元前4000年就开始使用铅。罗马人广泛使用铅制造水管和器皿，甚至用含铅化合物制作食品添加剂。'铅'(Lead)的元素符号Pb来自拉丁语'plumbum'。长期接触铅会导致严重的健康问题，这一点在20世纪才被广泛认识。现代社会已经大大减少了铅的使用，特别是在汽油、油漆和管道中。",
        imageUrl: "https://images.unsplash.com/photo-1578127033626-989754f5fae8?w=600&auto=format&fit=crop"
    },
    {
        number: 92,
        symbol: "U",
        name: "Uranium",
        chineseName: "铀",
        weight: "238.03",
        category: "actinide",
        group: 3, 
        period: 7,
        discoverer: "马丁·海因里希·克拉普罗特",
        year: "1789",
        story: "铀元素于1789年由德国化学家克拉普罗特在沥青铀矿中发现，并以当时新发现的天王星(Uranus)命名。铀的放射性直到1896年才被贝克勒尔发现。铀-235是唯一天然存在的可裂变同位素，可用于核反应堆和核武器。铀矿石常呈现黄绿色荧光，这使得它成为19世纪和20世纪初期玻璃和陶瓷的流行着色剂，直到其放射性危害被认识。",
        imageUrl: "https://images.unsplash.com/photo-1581922517927-ce1df90a5b55?w=600&auto=format&fit=crop"
    }
    // ... 后续将添加更多元素
]; 